[common.consensus_config]
max_message_len = 1048576
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
round_timeout = 3000
status_timeout = 5000
txs_block_limit = 1000

[common.general_config]
validators_count = 3

[common.services_config]

[node]
addr = "127.0.0.1:6332"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "31f4f91c35507c8224a2f23bad91f1e9c4fde0c98b44ae9b7bad4f61acb158bd"
service_key = "45d1f168eb6cbf36f9df3a3be3d6ca266ae62016205deb162d6a51ccaecfa0c4"
